addSbtPlugin("com.geirsson"              % "sbt-ci-release"                % "1.5.7")
addSbtPlugin("com.github.tkawachi"       % "sbt-doctest"                   % "0.9.9")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"                  % "0.1.20")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                      % "2.2.23")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"                  % "2.4.3")
addSbtPlugin("dev.guardrail" % "sbt-guardrail" % "0.75.1")
